<font size="6"> Introduction

The project is conducted to answer a question if a client is eligible for an approval of a loan application. Also most of the times. detailed reasons for rejections are not fully disclosed to clients. A machine learning model will be developed to provide counselling services.

In this notebook, data wrangliing will be conducted. The dataset will be accessed, organzied and cleaned to prepare it for an analysis in the future. The dataset, 'Loan Prediction Dataset' was obtained from Kaggle. 

<font size="5"> Import and Load

In [93]:
import numpy as np
import pandas as pd

In [94]:
#opening the data
df=pd.read_csv('../Capstone-3-/file/Training Data.csv')

In [95]:
df.head()

Id   Income  Age  Experience Married/Single House_Ownership Car_Ownership  \
0   1  1303834   23           3         single          rented            no   
1   2  7574516   40          10         single          rented            no   
2   3  3991815   66           4        married          rented            no   
3   4  6256451   41           2         single          rented           yes   
4   5  5768871   47          11         single          rented            no   

            Profession                 CITY           STATE  CURRENT_JOB_YRS  \
0  Mechanical_engineer                 Rewa  Madhya_Pradesh                3   
1   Software_Developer             Parbhani     Maharashtra                9   
2     Technical_writer            Alappuzha          Kerala                4   
3   Software_Developer          Bhubaneswar          Odisha                2   
4        Civil_servant  Tiruchirappalli[10]      Tamil_Nadu                3   

   CURRENT_HOUSE_YRS  Risk_Flag  
0                 13          0  
1                 13          0  
2                 10          0  
3                 12          1  
4                 14          1

Columns of the dataset were checked. 

In [96]:
df.shape

(252000, 13)

In [97]:
df.columns

Index(['Id', 'Income', 'Age', 'Experience', 'Married/Single',
       'House_Ownership', 'Car_Ownership', 'Profession', 'CITY', 'STATE',
       'CURRENT_JOB_YRS', 'CURRENT_HOUSE_YRS', 'Risk_Flag'],
      dtype='object')

General information of the dataset was loaded to check if it contains any missing values and data types. Also numerical columns were analyzed. 

In [98]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 252000 entries, 0 to 251999
Data columns (total 13 columns):
 #   Column             Non-Null Count   Dtype 
---  ------             --------------   ----- 
 0   Id                 252000 non-null  int64 
 1   Income             252000 non-null  int64 
 2   Age                252000 non-null  int64 
 3   Experience         252000 non-null  int64 
 4   Married/Single     252000 non-null  object
 5   House_Ownership    252000 non-null  object
 6   Car_Ownership      252000 non-null  object
 7   Profession         252000 non-null  object
 8   CITY               252000 non-null  object
 9   STATE              252000 non-null  object
 10  CURRENT_JOB_YRS    252000 non-null  int64 
 11  CURRENT_HOUSE_YRS  252000 non-null  int64 
 12  Risk_Flag          252000 non-null  int64 
dtypes: int64(7), object(6)
memory usage: 25.0+ MB


In [99]:
df.describe().T

count          mean           std      min         25%  \
Id                 252000.0  1.260005e+05  7.274628e+04      1.0    63000.75   
Income             252000.0  4.997117e+06  2.878311e+06  10310.0  2503015.00   
Age                252000.0  4.995407e+01  1.706385e+01     21.0       35.00   
Experience         252000.0  1.008444e+01  6.002590e+00      0.0        5.00   
CURRENT_JOB_YRS    252000.0  6.333877e+00  3.647053e+00      0.0        3.00   
CURRENT_HOUSE_YRS  252000.0  1.199779e+01  1.399037e+00     10.0       11.00   
Risk_Flag          252000.0  1.230000e-01  3.284379e-01      0.0        0.00   

                         50%         75%        max  
Id                  126000.5   189000.25   252000.0  
Income             5000694.5  7477502.00  9999938.0  
Age                     50.0       65.00       79.0  
Experience              10.0       15.00       20.0  
CURRENT_JOB_YRS          6.0        9.00       14.0  
CURRENT_HOUSE_YRS       12.0       13.00       14.0  
Risk_Flag                0.0        0.00        1.0

Column variables were checked to see if there are any misspelling.

<font size="5"> Missing values

Missing values for each columns were checked again.

In [100]:
df.isna().sum()

Id                   0
Income               0
Age                  0
Experience           0
Married/Single       0
House_Ownership      0
Car_Ownership        0
Profession           0
CITY                 0
STATE                0
CURRENT_JOB_YRS      0
CURRENT_HOUSE_YRS    0
Risk_Flag            0
dtype: int64

<font size="5"> Renaming the Columns and Variables

Column names were fixed for consistency.

In [101]:
df.rename(columns={'Married/Single': 'Marital_Status','CITY':'City','STATE':'State','CURRENT_JOB_YRS':'Job_Yrs','CURRENT_HOUSE_YRS':'House_Yrs'}, inplace=True)

In [102]:
df.head()

Id   Income  Age  Experience Marital_Status House_Ownership Car_Ownership  \
0   1  1303834   23           3         single          rented            no   
1   2  7574516   40          10         single          rented            no   
2   3  3991815   66           4        married          rented            no   
3   4  6256451   41           2         single          rented           yes   
4   5  5768871   47          11         single          rented            no   

            Profession                 City           State  Job_Yrs  \
0  Mechanical_engineer                 Rewa  Madhya_Pradesh        3   
1   Software_Developer             Parbhani     Maharashtra        9   
2     Technical_writer            Alappuzha          Kerala        4   
3   Software_Developer          Bhubaneswar          Odisha        2   
4        Civil_servant  Tiruchirappalli[10]      Tamil_Nadu        3   

   House_Yrs  Risk_Flag  
0         13          0  
1         13          0  
2         10          0  
3         12          1  
4         14          1

After, all columns' variables were checked for spelling or duplicated variables and observed numbers were attached on some of the city and state names. Therefore they were removed for futher analysis as well.

In [103]:
for col in df:
    print(df[col].unique())

[     1      2      3 ... 251998 251999 252000]
[1303834 7574516 3991815 ... 2843572 4522448 9070230]
[23 40 66 41 47 64 58 33 24 78 22 28 57 48 39 71 56 54 50 72 36 76 38 31
 52 59 21 26 55 45 77 63 30 25 73 75 27 74 67 46 68 79 42 60 32 65 49 35
 61 29 37 69 62 53 70 34 43 44 51]
[ 3 10  4  2 11  0 14 17 12  7  9  6  8  1 13 19 15 20  5 16 18]
['single' 'married']
['rented' 'norent_noown' 'owned']
['no' 'yes']
['Mechanical_engineer' 'Software_Developer' 'Technical_writer'
 'Civil_servant' 'Librarian' 'Economist' 'Flight_attendant' 'Architect'
 'Designer' 'Physician' 'Financial_Analyst' 'Air_traffic_controller'
 'Politician' 'Police_officer' 'Artist' 'Surveyor' 'Design_Engineer'
 'Chemical_engineer' 'Hotel_Manager' 'Dentist' 'Comedian'
 'Biomedical_Engineer' 'Graphic_Designer' 'Computer_hardware_engineer'
 'Petroleum_Engineer' 'Secretary' 'Computer_operator'
 'Chartered_Accountant' 'Technician' 'Microbiologist' 'Fashion_Designer'
 'Aviator' 'Psychologist' 'Magistrate' 'Lawyer' 'Firefi

In [104]:
print (df.City[df.City.str.endswith(']')])

4         Tiruchirappalli[10]
8                     Kota[6]
10                Hajipur[31]
12                  Erode[17]
15            Anantapuram[24]
                 ...         
251929        Nellore[14][15]
251933              Dehri[30]
251939             Kadapa[23]
251977             Purnia[26]
251985           Motihari[34]
Name: City, Length: 23299, dtype: object


Created list of city and state with numbers at the end with defined function.

In [105]:
def unclean_names(col):
    unclean_names = []
    for name in df[col].unique():
        if name.endswith(']'):
            unclean_names.append(name)
    return unclean_names

In [106]:
unclean_city_names = unclean_names('City')
unclean_state_names= unclean_names('State')

Removed numbers at the end of city and state names using a defined function.

In [107]:
def clean_df(df,col,unclean_list):
    for index,name in enumerate(df[col]):
        if name in unclean_list:
            if name.endswith(']'):
                name_ = name.strip('[]0123456789')
                df[col].iloc[index] = name_

In [111]:
clean_df(df,'State',unclean_state_names)

In [112]:
clean_df(df,'City',unclean_city_names)

Exported a new file with cleaned data.

In [113]:
df.head()

df.to_csv('loan_data.csv')

Id   Income  Age  Experience Marital_Status House_Ownership Car_Ownership  \
0   1  1303834   23           3         single          rented            no   
1   2  7574516   40          10         single          rented            no   
2   3  3991815   66           4        married          rented            no   
3   4  6256451   41           2         single          rented           yes   
4   5  5768871   47          11         single          rented            no   

            Profession             City           State  Job_Yrs  House_Yrs  \
0  Mechanical_engineer             Rewa  Madhya_Pradesh        3         13   
1   Software_Developer         Parbhani     Maharashtra        9         13   
2     Technical_writer        Alappuzha          Kerala        4         10   
3   Software_Developer      Bhubaneswar          Odisha        2         12   
4        Civil_servant  Tiruchirappalli      Tamil_Nadu        3         14   

   Risk_Flag  
0          0  
1          0  
2          0  
3          1  
4          1

<font size="5">  Conclusion

The data is cleaned and organized now and it is ready to be anaylzed and visualized in the future notebooks. Overall shape and information of the dataset was analyzed. The dataset had different formats of column names, therefore, they are renamed now for consistency and better interpretation in the future use. 

In the next notebook, the exploratory data analysis will be conducted to analyze the dataset and visualize the relationship between each features. The overall distribution of the dataset will be visualized in more details as well. 